server:
  tomcat:
    uri-encoding: UTF-8
  port: 8090

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://106.54.105.3:3306/pay?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: debian-sys-maint
    password: CvvMaaj7HcjUCo6u
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
  redis:
    database: 0 #索引
    host: 127.0.0.1
    port: 6379
#    password: foobared
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接

nacos:
  config:
    server-addr: 127.0.0.1:8848
feign:
  hystrix:
    enabled: true #是否开启断路器
mybatis:
  mapper-locations: classpath:mapper/*.xml

#分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
